// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmYY4zakN9UmCkuT6gl_7fmGyieoHiR0',
    appId: '1:308476875815:android:277b4c99a1c9af0c796a02',
    messagingSenderId: '308476875815',
    projectId: 'giga-sport-line',
    storageBucket: 'giga-sport-line.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucwT30VPvTXbYK1l-KSte4pSZcmzwDHg',
    appId: '1:308476875815:ios:c850a16e0f97b379796a02',
    messagingSenderId: '308476875815',
    projectId: 'giga-sport-line',
    storageBucket: 'giga-sport-line.appspot.com',
    androidClientId: '308476875815-l38cka0cj86k2p3mtpvd3bqvvccm3uh0.apps.googleusercontent.com',
    iosClientId: '308476875815-t1snvu2meo11v6pahvua0fj23lcrurrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigaSportFlutter',
  );
}
